In [1]:
import numpy as np
import pandas as pd
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [2]:
s[0]

1.0

In [3]:
df = pd.DataFrame(np.random.randn(6,4))
df

0         1         2         3
0  0.645870 -1.620442  1.034119  0.417360
1  0.089848 -2.156874  1.096625  1.097294
2 -0.631779 -1.291794 -0.114833  0.318145
3  1.792693 -0.258412 -0.398782  1.253556
4 -2.150572 -0.205028 -1.974984 -0.500412
5 -1.151564 -2.070326  0.976692 -0.520513

In [4]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6,4,),index=dates, columns=['A','B','C','D'])
df

A         B         C         D
2013-01-01 -0.121885  0.915700  0.033601  2.770818
2013-01-02 -2.663769  0.066421 -2.013109 -0.804124
2013-01-03  0.261968 -1.177993  1.579926 -0.561831
2013-01-04 -1.685668 -0.710373 -1.180895  0.882102
2013-01-05  2.525637  0.941236 -0.402726 -0.921485
2013-01-06 -0.791200  1.169315 -1.267052 -0.321655

In [7]:
df[0:1]

A       B         C         D
2013-01-01 -0.121885  0.9157  0.033601  2.770818

In [9]:
arr = np.arange(25)
print(arr)
arr = np.arange(25).reshape(5,5)
print(arr)

arr = np.arange(25)[:, np.newaxis]
print(arr)

arr = np.arange(25)[np.newaxis,:]
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]]
